title = "info-nf"
defaultContentLanguage = "fr"


[markup]
  [markup.tableOfContents]
    endLevel = 1
    ordered = true
    startLevel = 1


[languages.fr]
languageName = "Français"
weight = 1

[[module.imports]]
path = "github.com/imfing/hextra"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true

[markup.highlight]
noClasses = false

[[menu.main]]
name = "Sup"
pageRef = "/sup"
weight = 10

[[menu.main]]
name = "Spe"
pageRef = "/spe"
weight = 20

[[menu.main]]
name = "About"
pageRef = "/about"
weight = 30


[[menu.main]]
name = "Search"
weight = 50

  [menu.main.params]
  type = "search"

[params.navbar]
displayTitle = true
displayLogo = false

[params.footer]
displayCopyright = true
displayPoweredBy = false

[params.editURL]
enable = false
base = "https://github.com/"
