title = "info-nf"
defaultContentLanguage = "fr"
enableInlineShortcodes = true

# SEO and Meta Information
[params]
  description = "Ressources pédagogiques pour les cours d'informatique en CPGE - Classes Préparatoires aux Grandes Écoles"
  keywords = ["CPGE", "informatique", "programmation", "Python", "algorithmes", "cours", "éducation", "préparation", "grandes écoles"]
  author = "Info-NF"
  dateFormat = "2006-01-02"
  # Theme color scheme
  primaryColor = "#2563eb"  # Blue
  secondaryColor = "#1e40af"  # Darker blue
  accentColor = "#3b82f6"  # Light blue
  backgroundColor = "#ffffff"  # White
  textColor = "#1f2937"  # Dark gray
  lightTextColor = "#6b7280"  # Medium gray

[markup]
  [markup.tableOfContents]
    endLevel = 1
    ordered = true
    startLevel = 1


[languages.fr]
languageName = "Français"
weight = 1

[[module.imports]]
path = "github.com/imfing/hextra"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true

[markup.highlight]
noClasses = false

[[menu.main]]
name = "Sup"
pageRef = "/sup"
weight = 10

[[menu.main]]
name = "Spe"
pageRef = "/spe"
weight = 20

#[[menu.main]]
#name = "Blog"
#pageRef = "/blog"
#weight = 30

[[menu.main]]
name = "About"
pageRef = "/about"
weight = 30


[[menu.main]]
name = "Search"
weight = 50

  [menu.main.params]
  type = "search"

[params.navbar]
displayTitle = true
displayLogo = false

# Add navbar styling
style = "primary"
background = "light"
 [params.navbar.logo]
  path = "favicon.svg"
  dark = "favicon-dark.svg"
  link = "/"


[params.footer]
displayCopyright = true
displayPoweredBy = false
# Add footer styling
style = "light"
background = "light"

[params.editURL]
enable = false
base = "https://github.com/"

# Add social media meta tags
[params.social]
#  twitter = "@info_nf"
  github = "github.com/nf-info"
#  linkedin = "linkedin.com/company/info-nf"


[[menu.sidebar]]
name = "About"
pageRef = "/about"
weight = 1

#  [menu.sidebar.params]
#  type = "separator"

